### ISSUE TITLE
Tasks for 0.4.0

### ISSUE THREAD

**Issue by sveetch** [sveetch/cookiecutter-sveetch-python#13]
### Todo cookie

- [x] Use private setting like `_cookie_sveetch_python_version` in `cookiecutter.json` to write the current cookie version
- [x] Add `make project` to build in `dist/`
- [x] Add `cookiebaked.json` ?

### Todo template

- [x] #12 
- [x] #11 
- [x] #9
- [x] Upgrade application `__init__.py` to the modern way to load version;
- [x] Upgrade documentation to a new theme, improved sphinx_reload script and move it into docs/
- [x] Improve  Makefile (suffix bin path variables with `_BIN` and add missing var `PYTHON_BIN`) 
- [x] Include README in `docs/index` instead of duplicating it
- [x] Don't test all supported Python version in tox config, only the min and max
- [x] Split extra requirements into various accurate extra spaces (dev, quality,  release, etc..) to avoid making Tox installing useless stuff (like Flake8) for testing;
- [x] Flake task should be something like `$(FLAKE_BIN) --statistics --show-source $(APPLICATION_NAME) tests` (add statistics and use a single job for app and tests lint)

### Finally

- [x] Update repository sample with 0.4.0
